query GetCharacters($page: Int, $name: String) {
  characters(page: $page, filter: { name: $name }) {
    info {
      count
      pages
    }
    results {
      name
      image
      id
      origin {
        dimension
      }
    }
  }
}

query GetCharacter($id: ID!) {
  character(id : $id) {
    name
    image
    status
    gender
    species
    location {
      dimension
      name
      type
    }
    episode {
      name
      air_date
    }
  }
}